/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package todoNew




import io.ktor.application.*
import io.ktor.features.*
import io.ktor.http.*
import io.ktor.jackson.*
import io.ktor.response.*
import io.ktor.routing.*

fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)
//val todos = listOf(todo1, todo2)
fun Application.module(testing: Boolean = false) {
    install(Routing){
        todoApi()
    }
    install(StatusPages){
        this.exception<Throwable> { e ->
            call.respondText (e.localizedMessage, ContentType.Text.Plain)
            throw e
        }

    }
    install(ContentNegotiation){
        jackson {

        }
    }

}
